sonar.projectKey=hoagg-2603_Scan_to_text
sonar.organization=3ae267d02d9d3e52064578dff74d18f4496361dc

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=Scan_to_text
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Exclude patterns
sonar.exclusions=**/*.spec.js,**/tests/**,**/node_modules/**,**/dist/**,**/build/**,**/__pycache__/**,**/venv/**,.git/**,docker-data/**,logs/**,uploads/**

# Python specific
sonar.python.version=3.11

# JavaScript specific
sonar.javascript.file.suffixes=.js,.jsx

# Coverage
sonar.coverage.exclusions=**/tests/**,**/*.test.js,**/node_modules/**
