"""scan packages

Revision ID: 0011_scan_packages
Revises: 0010_case_input_assignment
Create Date: 2026-10-04 22:55:51.678766
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0011_scan_packages'
down_revision: Union[str, Sequence[str], None] = '0010_case_input_assignment'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
