"""Generate the immutable schema snapshot used by the Alembic baseline.

This command is intentionally opt-in. Once the baseline is committed, schema
changes belong in a new Alembic revision instead of regenerating revision 0001.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from pprint import pformat
import sys

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    DateTime,
    Integer,
    String,
    Text,
    UniqueConstraint,
)

ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT_PATH = ROOT / "migrations" / "schema_0001.py"
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from server.models import Base


LEGACY_BASELINE_FOREIGN_KEY_OMISSIONS = {
    (
        "submission_review_histories",
        "confirmed_by_user_id",
        "users.id",
    ),
}


def _type_spec(column_type) -> dict:
    if isinstance(column_type, BigInteger):
        return {"name": "big_integer"}
    if isinstance(column_type, Integer):
        return {"name": "integer"}
    if isinstance(column_type, Text):
        return {"name": "text"}
    if isinstance(column_type, String):
        return {"name": "string", "length": column_type.length}
    if isinstance(column_type, DateTime):
        return {"name": "datetime", "timezone": bool(column_type.timezone)}
    if isinstance(column_type, Boolean):
        return {"name": "boolean"}
    raise TypeError(f"Unsupported baseline column type: {column_type!r}")


def build_snapshot() -> dict:
    tables = []
    for table in Base.metadata.sorted_tables:
        columns = []
        for column in table.columns:
            foreign_keys = [
                {
                    "target": foreign_key.target_fullname,
                    "ondelete": foreign_key.ondelete,
                }
                for foreign_key in column.foreign_keys
                if (
                    table.name,
                    column.name,
                    foreign_key.target_fullname,
                ) not in LEGACY_BASELINE_FOREIGN_KEY_OMISSIONS
            ]
            columns.append({
                "name": str(column.name),
                "type": _type_spec(column.type),
                "nullable": bool(column.nullable),
                "primary_key": bool(column.primary_key),
                "foreign_keys": foreign_keys,
                "quote": getattr(column.name, "quote", None),
            })

        constraints = []
        for constraint in table.constraints:
            if isinstance(constraint, UniqueConstraint):
                constraints.append({
                    "kind": "unique",
                    "name": constraint.name,
                    "columns": [column.name for column in constraint.columns],
                })
            elif isinstance(constraint, CheckConstraint):
                constraints.append({
                    "kind": "check",
                    "name": constraint.name,
                    "sqltext": str(constraint.sqltext),
                })

        indexes = [
            {
                "name": index.name,
                "unique": bool(index.unique),
                "columns": [column.name for column in index.columns],
            }
            for index in sorted(table.indexes, key=lambda item: item.name or "")
        ]
        tables.append({
            "name": table.name,
            "columns": columns,
            "constraints": sorted(
                constraints,
                key=lambda item: (
                    item["kind"],
                    item.get("name") or "",
                    tuple(item.get("columns", [])),
                ),
            ),
            "indexes": indexes,
        })
    return {"tables": tables}


def render_snapshot(snapshot: dict) -> str:
    canonical = json.dumps(snapshot, ensure_ascii=False, sort_keys=True)
    digest = hashlib.sha256(canonical.encode("utf-8")).hexdigest()
    payload = pformat(snapshot, width=100, sort_dicts=True)
    return f'''"""Frozen SQLAlchemy schema for Alembic revision 0001.

Generated by scripts/generate_migration_schema_snapshot.py. Do not regenerate
after the baseline has shipped; add a new Alembic revision instead.
"""

from __future__ import annotations

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    Column,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    String,
    Table,
    Text,
    UniqueConstraint,
)
from sqlalchemy.sql.elements import quoted_name


SCHEMA_SHA256 = "{digest}"
SCHEMA = {payload}


def _column_type(spec: dict):
    name = spec["name"]
    if name == "integer":
        return Integer()
    if name == "big_integer":
        return BigInteger()
    if name == "string":
        return String(length=spec.get("length"))
    if name == "datetime":
        return DateTime(timezone=bool(spec.get("timezone")))
    if name == "boolean":
        return Boolean()
    if name == "text":
        return Text()
    raise ValueError(f"Unsupported baseline type: {{name}}")


def build_metadata() -> MetaData:
    metadata = MetaData()
    for table_spec in SCHEMA["tables"]:
        columns = []
        for column_spec in table_spec["columns"]:
            args = []
            for foreign_key in column_spec["foreign_keys"]:
                args.append(ForeignKey(
                    foreign_key["target"],
                    ondelete=foreign_key.get("ondelete"),
                ))
            name = column_spec["name"]
            if column_spec.get("quote") is not None:
                name = quoted_name(name, column_spec["quote"])
            columns.append(Column(
                name,
                _column_type(column_spec["type"]),
                *args,
                nullable=column_spec["nullable"],
                primary_key=column_spec["primary_key"],
            ))

        constraints = []
        for constraint_spec in table_spec["constraints"]:
            if constraint_spec["kind"] == "unique":
                constraints.append(UniqueConstraint(
                    *constraint_spec["columns"],
                    name=constraint_spec.get("name"),
                ))
            elif constraint_spec["kind"] == "check":
                constraints.append(CheckConstraint(
                    constraint_spec["sqltext"],
                    name=constraint_spec.get("name"),
                ))
        Table(table_spec["name"], metadata, *columns, *constraints)

    for table_spec in SCHEMA["tables"]:
        table = metadata.tables[table_spec["name"]]
        for index_spec in table_spec["indexes"]:
            Index(
                index_spec["name"],
                *(table.c[column] for column in index_spec["columns"]),
                unique=index_spec["unique"],
            )
    return metadata
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--write",
        action="store_true",
        help="Write migrations/schema_0001.py. Otherwise only print its digest.",
    )
    args = parser.parse_args()
    snapshot = build_snapshot()
    rendered = render_snapshot(snapshot)
    if args.write:
        SNAPSHOT_PATH.parent.mkdir(parents=True, exist_ok=True)
        SNAPSHOT_PATH.write_text(rendered, encoding="utf-8")
    digest = hashlib.sha256(
        json.dumps(snapshot, ensure_ascii=False, sort_keys=True).encode("utf-8")
    ).hexdigest()
    print(digest)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
