// Phần mở đầu của đề cương + Mở đầu, Chương 1, Chương 2.
// Mỗi mục: [tiêu đề, mục đích, nội dung (mảng, mảng con = gạch đầu dòng cấp 2), hình/bảng dự kiến, kết quả]
module.exports.front = {
  urgency: [
    'Luật Lưu trữ năm 2024 và chủ trương chuyển đổi số quốc gia đặt ra yêu cầu số hóa tài liệu lưu trữ giấy tại các cơ quan, tổ chức. Phần lớn khối lượng này được thuê ngoài cho các đơn vị thi công số hóa. Một dự án điển hình có hàng chục nghìn trang tài liệu, hàng chục nhân sự và nhiều công đoạn nối tiếp nhau: chỉnh lý, scan, kiểm tra scan, nhập metadata, kiểm tra nhập liệu, chuẩn hóa và bàn giao.',
    'Khảo sát tại một đơn vị thi công số hóa cho thấy: tiến độ và chất lượng đang được theo dõi bằng bảng tính Excel; số trang, số file giữa scan và kiểm tra thường lệch nhau mà không có cơ chế xử lý; việc nhập metadata cho từng văn bản (tên loại, số ký hiệu, ngày ban hành, cơ quan ban hành, trích yếu…) hoàn toàn thủ công và chiếm nhiều nhân lực nhất, phải thuê 20 đến 100 cộng tác viên; sản lượng và tiền công được tính tay.',
    'Trong khi đó, văn bản hành chính Việt Nam có thể thức trình bày được quy định thống nhất, các thành phần như số ký hiệu, ngày tháng, tên cơ quan nằm ở vị trí tương đối cố định. Đây là điều kiện thuận lợi để ứng dụng nhận dạng ký tự quang học (OCR) và trích xuất thông tin tự động, giúp giảm thời gian nhập liệu mà vẫn giữ con người là người kiểm duyệt cuối cùng.',
    'Từ thực tế đó, đề tài xây dựng một hệ thống web quản lý khép kín quy trình thi công số hóa, tích hợp module OCR trích xuất tự động thông tin văn bản hành chính, có kiểm soát chất lượng và đánh giá định lượng trên dữ liệu thực tế.',
  ],
  goals: [
    'Xây dựng hệ thống quản lý 7 công đoạn số hóa: theo dõi trạng thái từng hộp, hồ sơ, file; giao việc, thu hồi, phân lại; truy vết ai làm gì, khi nào.',
    'Kiểm soát chất lượng tại nguồn: so khớp mục lục chỉnh lý với kết quả scan, kiểm tra scan 100%, kiểm tra nhập liệu hai vòng (100% và lấy mẫu 30%).',
    'Xây dựng module OCR trích xuất tự động 5 trường thông tin văn bản hành chính (tên loại, số và ký hiệu, ngày ban hành, cơ quan ban hành, trích yếu) và gợi ý vào màn hình nhập liệu.',
    'Phát hiện tự động ảnh scan kém chất lượng (mờ, nghiêng, trang trắng, độ phân giải thấp) để tăng độ chính xác OCR.',
    'Tính sản lượng theo trang, KPI, chi trả cộng tác viên; chuẩn hóa đầu ra (PDF/A, ký số, gói tin SIP) và bàn giao.',
    'Đánh giá định lượng: so sánh các engine OCR tiếng Việt, độ chính xác trích xuất theo từng trường, thời gian nhập liệu tiết kiệm được.',
  ],
  scope: [
    '**Đối tượng nghiên cứu:** quy trình thi công số hóa tài liệu lưu trữ hành chính; kỹ thuật OCR tiếng Việt và trích xuất thông tin từ văn bản hành chính.',
    '**Phạm vi tài liệu:** văn bản hành chính dạng in (công văn, quyết định, nghị quyết, thông báo…), scan ở 200 dpi; không xử lý chữ viết tay, bản đồ, bản vẽ kỹ thuật.',
    '**Phạm vi hệ thống:** ứng dụng web chạy trên máy tính (Chrome, Edge); máy chủ đặt tại đơn vị; khoảng 50 tài khoản nội bộ và tối đa 100 cộng tác viên đồng thời; khoảng 20.000 file PDF mỗi dự án.',
    '**Ngoài phạm vi:** tính lương kế toán, quản lý thiết bị, ứng dụng di động, tích hợp trực tiếp với phần mềm ký số (hệ thống chỉ quản lý trạng thái ký).',
  ],
  methods: [
    '**Khảo sát và phân tích nghiệp vụ:** phỏng vấn đơn vị thi công, phân tích file thống kê, phiếu yêu cầu dự án thật; lập tài liệu đặc tả yêu cầu (BA) có mã truy vết.',
    '**Thiết kế hướng đối tượng và mô hình hóa:** UML (use case, hoạt động, trạng thái, tuần tự), mô hình thực thể liên kết.',
    '**Phát triển lặp:** chia theo module, mỗi module có kiểm thử tự động, quản lý mã nguồn bằng Git, mỗi nhiệm vụ một commit.',
    '**Thực nghiệm:** xây dựng bộ dữ liệu có nhãn từ kết quả kiểm tra của con người; đo CER, độ chính xác theo trường, thời gian nhập; so sánh có/không có gợi ý.',
  ],
};

module.exports.chapters = [
  ['MỞ ĐẦU', 'Giới thiệu bối cảnh, lý do, mục tiêu, phạm vi, phương pháp và cấu trúc của báo cáo.', [
    ['Lý do chọn đề tài',
      'Trình bày tính cấp thiết của đề tài từ yêu cầu chuyển đổi số và thực tế thi công số hóa.',
      ['Yêu cầu số hóa tài liệu lưu trữ theo Luật Lưu trữ 2024 và chủ trương chuyển đổi số.',
        'Thực trạng quản lý thủ công bằng Excel tại đơn vị thi công: không truy vết, lệch số liệu, nhập liệu tốn nhân lực.',
        'Cơ hội ứng dụng OCR nhờ thể thức văn bản hành chính được chuẩn hóa.'],
      'Không có', 'Nêu rõ bài toán thực tế mà đề tài giải quyết.'],
    ['Mục tiêu và nhiệm vụ của đề tài',
      'Xác định mục tiêu tổng quát và các mục tiêu cụ thể có thể đo lường.',
      ['Mục tiêu tổng quát: hệ thống quản lý khép kín quy trình số hóa tích hợp OCR.',
        'Các nhiệm vụ: khảo sát, phân tích, thiết kế, xây dựng, thực nghiệm, triển khai.',
        'Tiêu chí đánh giá hoàn thành cho từng nhiệm vụ.'],
      'Không có', 'Danh sách mục tiêu cụ thể làm căn cứ đánh giá ở Chương 5.'],
    ['Đối tượng và phạm vi nghiên cứu',
      'Giới hạn rõ những gì đề tài làm và không làm.',
      ['Đối tượng: quy trình thi công số hóa, văn bản hành chính dạng in, kỹ thuật OCR tiếng Việt.',
        'Phạm vi về loại tài liệu, quy mô người dùng, môi trường triển khai.',
        'Các nội dung nằm ngoài phạm vi và lý do.'],
      'Không có', 'Ranh giới đề tài rõ ràng.'],
    ['Phương pháp thực hiện',
      'Trình bày cách tiếp cận để đạt mục tiêu.',
      ['Khảo sát thực tế và phân tích nghiệp vụ.', 'Mô hình hóa UML và thiết kế cơ sở dữ liệu.', 'Phát triển lặp có kiểm thử tự động.', 'Thực nghiệm định lượng với dữ liệu có nhãn.'],
      'Không có', 'Phương pháp phù hợp với từng nhiệm vụ.'],
    ['Bố cục báo cáo',
      'Tóm tắt nội dung từng chương.',
      ['Chương 1 đến Chương 5, Kết luận, Phụ lục.'],
      'Không có', 'Người đọc nắm được mạch của báo cáo.'],
  ]],

  ['CHƯƠNG 1. TỔNG QUAN VỀ SỐ HÓA TÀI LIỆU LƯU TRỮ VÀ BÀI TOÁN TRÍCH XUẤT THÔNG TIN',
    'Chương này trình bày nền tảng nghiệp vụ của đề tài: số hóa tài liệu lưu trữ là gì, quy trình thi công diễn ra thế nào, văn bản hành chính có thể thức ra sao, hiện trạng tại đơn vị khảo sát và các sản phẩm liên quan, từ đó phát biểu bài toán.', [
    ['1.1. Số hóa tài liệu lưu trữ và quy trình thi công số hóa',
      'Giúp người đọc hiểu nghiệp vụ mà hệ thống phục vụ.',
      ['Khái niệm tài liệu lưu trữ, số hóa tài liệu lưu trữ, phông lưu trữ, hộp, hồ sơ, văn bản.',
        'Mục đích và lợi ích của số hóa: bảo quản bản gốc, khai thác nhanh, chuyển đổi số.',
        'Bảy công đoạn thi công số hóa:',
        ['Chỉnh lý: phân loại, lập hồ sơ, lập mục lục (năm, cơ quan, thể loại, hộp, hồ sơ).',
          'Scan: chuyển tài liệu giấy thành file ảnh/PDF theo cấu trúc thư mục quy định.',
          'Kiểm tra scan: đối chiếu số trang, số file, chất lượng ảnh.',
          'Nhập liệu: nhập metadata hồ sơ và văn bản.',
          'Kiểm tra nhập liệu: soát lỗi, sửa, duyệt.',
          'Chuẩn hóa: làm sạch tên file, chuyển PDF/A, ký số, đóng gói.',
          'Bàn giao và nghiệm thu.'],
        'Các vai trò tham gia: quản trị dự án, nhân sự hành chính, cộng tác viên nhập liệu, khách hàng.'],
      'Hình 1.1: Sơ đồ 7 công đoạn thi công số hóa. Bảng 1.1: Vai trò và công việc trong dự án số hóa.',
      'Mô tả đầy đủ nghiệp vụ làm cơ sở cho phân tích ở Chương 3.'],
    ['1.2. Thể thức văn bản hành chính và metadata hồ sơ, tài liệu',
      'Làm rõ cấu trúc văn bản hành chính, là cơ sở để thiết kế module OCR trích xuất thông tin.',
      ['Các thành phần thể thức của văn bản hành chính và vị trí trình bày trên trang:',
        ['Tên cơ quan ban hành và số, ký hiệu văn bản ở phía trên bên trái.',
          'Quốc hiệu, tiêu ngữ, địa danh và ngày tháng ban hành ở phía trên bên phải.',
          'Tên loại văn bản và trích yếu nội dung ở giữa trang.',
          'Nội dung, chữ ký, con dấu, nơi nhận ở các phần tiếp theo.'],
        'Quy ước ghi số, ký hiệu (ví dụ 123/QĐ-BYT), ngày tháng năm, tên loại văn bản.',
        'Metadata hồ sơ (18 trường: mã hồ sơ, tiêu đề, thời hạn lưu trữ, thời gian bắt đầu/kết thúc, số tờ…) và metadata văn bản (22 trường).',
        'Danh mục mã: thời hạn lưu trữ, chế độ sử dụng, ngôn ngữ, tên loại văn bản.',
        'Năm trường được chọn làm đối tượng trích xuất tự động và lý do chọn.'],
      'Hình 1.2: Bố cục các thành phần thể thức trên trang đầu văn bản. Bảng 1.2: Danh sách trường metadata văn bản và trường được trích xuất tự động.',
      'Xác định đầu ra cụ thể của bài toán OCR.'],
    ['1.3. Hiện trạng và khó khăn tại đơn vị thi công số hóa',
      'Chứng minh bài toán có thật bằng số liệu khảo sát.',
      ['Cách quản lý hiện tại: theo dõi theo hộp trên Excel (số trang, số file scan và kiểm tra, ngày giao, người làm).',
        'Số liệu khảo sát từ file thống kê: số hộp, số hồ sơ, số trang, độ lệch trang/file giữa scan và kiểm tra.',
        'Các vấn đề: không truy vết, dữ liệu không thống nhất (cùng một tên viết nhiều kiểu), sản lượng tính tay, nhập liệu thủ công tốn nhân lực.',
        'Phần mềm nhập liệu hiện có: những gì đã có và còn thiếu.',
        'Yêu cầu bảo mật: dữ liệu nhạy cảm, máy chủ đặt tại đơn vị.'],
      'Bảng 1.3: Số liệu khảo sát dự án mẫu. Hình 1.3: Ví dụ bảng theo dõi Excel hiện tại.',
      'Danh sách vấn đề cụ thể mà hệ thống cần giải quyết.'],
    ['1.4. Khảo sát các sản phẩm và công trình liên quan',
      'Xác định giải pháp đã có và điểm mới của đề tài.',
      ['Sản phẩm thương mại trong nước về OCR và trích xuất văn bản (VNPT SmartReader, FPT.AI Reader, SmartDoc).',
        'Phần mềm mã nguồn mở: Archivematica (bảo quản theo OAIS), Paperless-ngx (quản lý tài liệu có OCR), OCRmyPDF.',
        'Thư viện OCR tiếng Việt: VietOCR, PaddleOCR, Tesseract.',
        'Các luận văn, đồ án liên quan về số hóa và OCR tiếng Việt.',
        'Bảng so sánh theo các tiêu chí: quản lý quy trình, kiểm soát chất lượng, OCR, trích xuất, chạy nội bộ.'],
      'Bảng 1.4: So sánh các sản phẩm liên quan với đề tài.',
      'Chỉ ra khoảng trống: chưa có hệ thống kết hợp quản lý thi công nhiều công đoạn với OCR hỗ trợ nhập liệu, chạy nội bộ.'],
    ['1.5. Phát biểu bài toán và hướng giải quyết',
      'Phát biểu chính xác hai bài toán của đề tài.',
      ['Bài toán 1, quản lý quy trình: đầu vào, đầu ra, ràng buộc (truy vết, kiểm soát chất lượng, phân quyền).',
        'Bài toán 2, trích xuất thông tin:',
        ['Đầu vào: file PDF scan văn bản hành chính, 200 dpi, đã qua kiểm tra scan.',
          'Đầu ra: 5 trường thông tin kèm độ tin cậy.',
          'Tiêu chí: độ chính xác theo từng trường, thời gian xử lý, chạy trên máy chủ nội bộ.'],
        'Hướng giải quyết tổng quát và kiến trúc sơ bộ.'],
      'Hình 1.4: Kiến trúc tổng quát của giải pháp.',
      'Bài toán được phát biểu rõ, làm căn cứ cho các chương sau.'],
  ]],

  ['CHƯƠNG 2. CƠ SỞ LÝ THUYẾT VÀ CÔNG NGHỆ',
    'Chương này trình bày các kiến thức và công nghệ được sử dụng: kiến trúc ứng dụng web, máy trạng thái, xử lý ảnh, OCR, trích xuất thông tin, các chuẩn lưu trữ và phương pháp đánh giá.', [
    ['2.1. Kiến trúc ứng dụng web và các công nghệ xây dựng hệ thống',
      'Giải thích lựa chọn công nghệ cho phần hệ thống.',
      ['Kiến trúc nhiều lớp: router, service, repository; lợi ích tách biệt truy vấn dữ liệu và nghiệp vụ.',
        'Python và FastAPI: định tuyến, kiểm tra dữ liệu với Pydantic, dependency injection cho phân quyền.',
        'SQLAlchemy và PostgreSQL: ánh xạ đối tượng, giao dịch, khóa dòng chống tranh chấp.',
        'Alembic: quản lý phiên bản cơ sở dữ liệu, migration không làm hỏng dữ liệu cũ.',
        'Giao diện: HTML, JavaScript, Bootstrap, PDF.js; chính sách bảo mật nội dung (CSP).',
        'Xác thực JWT, băm mật khẩu scrypt, phân quyền theo vai trò.'],
      'Hình 2.1: Kiến trúc nhiều lớp của hệ thống. Bảng 2.1: Công nghệ sử dụng và lý do chọn.',
      'Cơ sở để trình bày thiết kế kiến trúc ở mục 3.6.'],
    ['2.2. Mô hình máy trạng thái trong quản lý quy trình',
      'Trình bày lý thuyết dùng để điều khiển quy trình 7 công đoạn.',
      ['Khái niệm máy trạng thái hữu hạn: trạng thái, sự kiện, chuyển trạng thái, điều kiện.',
        'Áp dụng cho quy trình: chờ, đang làm, hoàn tất, bị trả lại; điều kiện mở công đoạn sau.',
        'Vòng làm lại (rework) khi công đoạn kiểm tra trả về.',
        'Ghi sự kiện bất biến (event log) để truy vết và kiểm toán.'],
      'Hình 2.2: Ví dụ biểu đồ trạng thái của một công đoạn.',
      'Cơ sở cho thiết kế mục 3.4.'],
    ['2.3. Tiền xử lý ảnh tài liệu scan',
      'Trình bày các kỹ thuật làm ảnh tốt hơn trước khi OCR và kỹ thuật phát hiện ảnh kém chất lượng.',
      ['Chuyển ảnh xám, nhị phân hóa (Otsu, ngưỡng thích nghi).',
        'Khử nhiễu, chỉnh độ nghiêng (biến đổi Hough, chiếu ngang).',
        'Đánh giá độ mờ bằng phương sai toán tử Laplace; phát hiện trang trắng.',
        'Kiểm tra độ phân giải và độ sâu màu theo yêu cầu số hóa (200 dpi, 24 bit).',
        'Thư viện OpenCV.'],
      'Hình 2.3: Ảnh trước và sau tiền xử lý. Hình 2.4: Ví dụ ảnh mờ, nghiêng và điểm đánh giá.',
      'Lựa chọn kỹ thuật cho bước tiền xử lý và kiểm tra chất lượng ảnh.'],
    ['2.4. Nhận dạng ký tự quang học (OCR) cho tiếng Việt',
      'Trình bày lý thuyết OCR và các engine sẽ so sánh.',
      ['Quy trình OCR: phát hiện vùng chữ, nhận dạng dòng chữ, hậu xử lý.',
        'Khó khăn riêng của tiếng Việt: dấu thanh, dấu phụ, chữ in nghiêng, con dấu đè chữ.',
        'Tesseract: kiến trúc LSTM, mô hình tiếng Việt có sẵn.',
        'VietOCR: kiến trúc CNN kết hợp Transformer hoặc Seq2Seq cho dòng chữ tiếng Việt.',
        'PaddleOCR: phát hiện và nhận dạng chữ, phân tích bố cục tài liệu.',
        'Ưu nhược điểm và tiêu chí lựa chọn.'],
      'Hình 2.5: Quy trình OCR tổng quát. Bảng 2.2: So sánh lý thuyết ba engine OCR.',
      'Lựa chọn các engine đưa vào thực nghiệm ở mục 5.2.'],
    ['2.5. Trích xuất thông tin từ văn bản hành chính',
      'Trình bày các cách tiếp cận để lấy 5 trường từ kết quả OCR.',
      ['Tiếp cận dựa trên luật: biểu thức chính quy cho số ký hiệu, ngày tháng; danh sách tên loại văn bản.',
        'Tiếp cận dựa trên vị trí: chia vùng theo thể thức văn bản (trên trái, trên phải, giữa trang).',
        'Tiếp cận học máy: nhận dạng thực thể có tên; mô hình hiểu bố cục tài liệu (LayoutLM); mô hình ngôn ngữ chạy cục bộ.',
        'Kết hợp các cách tiếp cận và tính độ tin cậy cho từng trường.',
        'Chuẩn hóa giá trị: ngày về định dạng DD/MM/YYYY, tên loại về mã danh mục.'],
      'Hình 2.6: Các vùng thông tin trên trang đầu văn bản. Bảng 2.3: Mẫu nhận dạng cho từng trường.',
      'Lựa chọn phương pháp trích xuất cho thiết kế mục 3.7.'],
    ['2.6. Các chuẩn lưu trữ: PDF/A, chữ ký số, gói tin SIP',
      'Trình bày các chuẩn đầu ra mà công đoạn chuẩn hóa và bàn giao phải đáp ứng.',
      ['PDF/A (ISO 19005): đặc điểm, mức tuân thủ, công cụ chuyển đổi và kiểm tra (OCRmyPDF, veraPDF).',
        'Chữ ký số trên PDF: nguyên lý, vị trí hiển thị, kiểm tra hiệu lực.',
        'Mô hình OAIS (ISO 14721) và gói tin SIP: thành phần gói, thông tin mô tả gói và phông.',
        'Mã băm SHA-256 để bảo đảm toàn vẹn file khi bàn giao.'],
      'Bảng 2.4: Yêu cầu kỹ thuật đối với file số hóa.',
      'Cơ sở cho chức năng chuẩn hóa và bàn giao.'],
    ['2.7. Phương pháp đánh giá: CER, độ chính xác theo trường',
      'Xác định các thước đo dùng trong Chương 5.',
      ['Tỉ lệ lỗi ký tự (CER) và tỉ lệ lỗi từ (WER) dựa trên khoảng cách chỉnh sửa Levenshtein.',
        'Độ chính xác khớp chính xác (exact match) và khớp sau chuẩn hóa cho từng trường.',
        'Precision, Recall, F1 khi trường có thể thiếu.',
        'Đo thời gian nhập liệu và tỉ lệ trường phải sửa.',
        'Thiết kế thí nghiệm có đối chứng (có gợi ý và không gợi ý).'],
      'Bảng 2.5: Các thước đo và công thức.',
      'Bộ thước đo thống nhất cho thực nghiệm.'],
  ]],
];
