// Chương 5, Kết luận, Tài liệu tham khảo, Phụ lục; kế hoạch, viết tắt.
module.exports.chapters = [
  ['CHƯƠNG 5. THỰC NGHIỆM VÀ ĐÁNH GIÁ',
    'Chương này đánh giá định lượng module OCR và kiểm thử toàn bộ hệ thống, so sánh kết quả với mục tiêu đã đặt ra.', [
    ['5.1. Xây dựng bộ dữ liệu đánh giá',
      'Chuẩn bị dữ liệu có nhãn đáng tin cậy để đo độ chính xác.',
      ['Nguồn dữ liệu: các văn bản đã qua kiểm tra nhập liệu vòng 1 và vòng 2 trong dự án thật; giá trị đã duyệt là nhãn đúng.',
        'Quy mô dự kiến: 300 đến 500 văn bản, phân bố theo tên loại (công văn, quyết định, nghị quyết, thông báo…).',
        'Chia tập phát triển và tập kiểm tra; đảm bảo không trùng văn bản.',
        'Mô tả thống kê: số trang, chất lượng ảnh, tỉ lệ văn bản có con dấu đè chữ.',
        'Xử lý dữ liệu nhạy cảm: chỉ dùng trên máy chủ nội bộ, ẩn thông tin khi đưa vào báo cáo.'],
      'Bảng 5.1: Thống kê bộ dữ liệu. Hình 5.1: Phân bố văn bản theo tên loại.',
      'Bộ dữ liệu đủ lớn và đại diện cho dự án thật.'],
    ['5.2. So sánh các engine OCR tiếng Việt',
      'Chọn engine OCR phù hợp nhất cho bài toán.',
      ['Thiết lập thí nghiệm: cùng ảnh đầu vào, cùng bước tiền xử lý, cùng phần cứng.',
        'Engine so sánh: Tesseract, VietOCR, PaddleOCR.',
        'Thước đo: CER, WER trên từng vùng thông tin; thời gian xử lý một trang.',
        'Ảnh hưởng của tiền xử lý: so sánh có và không có chỉnh nghiêng, khử nhiễu.',
        'Phân tích lỗi điển hình: mất dấu, nhầm số, lỗi do con dấu.'],
      'Bảng 5.2: CER, WER và thời gian của từng engine. Hình 5.2: Biểu đồ so sánh CER. Bảng 5.3: Ví dụ lỗi điển hình.',
      'Engine được chọn có căn cứ số liệu.'],
    ['5.3. Đánh giá độ chính xác trích xuất theo từng trường',
      'Đo chất lượng trích xuất 5 trường.',
      ['Độ chính xác khớp chính xác và khớp sau chuẩn hóa cho: tên loại, số và ký hiệu, ngày ban hành, cơ quan ban hành, trích yếu.',
        'Precision, Recall, F1 khi trường không trích xuất được.',
        'Mối quan hệ giữa độ tin cậy và độ chính xác; chọn ngưỡng tô màu cảnh báo.',
        'So sánh cách tiếp cận dựa trên luật, dựa trên vị trí và kết hợp.',
        'Phân tích các trường hợp sai và hướng cải thiện.'],
      'Bảng 5.4: Độ chính xác theo từng trường. Hình 5.3: Biểu đồ độ chính xác theo ngưỡng tin cậy.',
      'Biết rõ trường nào AI làm tốt, trường nào cần người kiểm tra kỹ.'],
    ['5.4. Đánh giá hiệu quả hỗ trợ nhập liệu',
      'Đo lợi ích thực tế đối với người nhập liệu.',
      ['Thí nghiệm đối chứng: cùng người nhập, cùng khối lượng văn bản, có và không có gợi ý.',
        'Thước đo: thời gian nhập trung bình một văn bản, số trường phải sửa, tỉ lệ lỗi sau kiểm tra.',
        'Ước tính số giờ công và chi phí tiết kiệm cho một dự án 20.000 file.',
        'Khảo sát ý kiến người nhập liệu.'],
      'Bảng 5.5: Thời gian và tỉ lệ lỗi khi có/không có gợi ý. Hình 5.4: Biểu đồ thời gian nhập liệu.',
      'Chứng minh hiệu quả bằng số liệu.'],
    ['5.5. Kiểm thử chức năng và hiệu năng hệ thống',
      'Bảo đảm hệ thống đúng yêu cầu và chịu được tải.',
      ['Kiểm thử tự động: kiểm thử đơn vị và tích hợp cho máy trạng thái, phân quyền, API (pytest).',
        'Kiểm thử chấp nhận theo các kịch bản UAT gắn với yêu cầu.',
        'Kiểm thử hiệu năng: 100 người dùng đồng thời, thời gian mở PDF, thời gian nộp gói scan (Locust).',
        'Kiểm thử bảo mật cơ bản: phân quyền, cộng tác viên không tải được PDF, cách ly dữ liệu theo dự án.',
        'Kiểm thử sao lưu và khôi phục.'],
      'Bảng 5.6: Kết quả kiểm thử tự động. Bảng 5.7: Kết quả kiểm thử chấp nhận. Bảng 5.8: Kết quả kiểm thử hiệu năng.',
      'Hệ thống đạt các tiêu chí chấp nhận.'],
    ['5.6. Kết quả vận hành thực tế',
      'Đánh giá hệ thống khi chạy thật tại đơn vị.',
      ['Kết quả chạy thử với một số hộp hồ sơ và nhóm cộng tác viên.',
        'Số liệu vận hành: số hộp, hồ sơ, trang đã xử lý; tỉ lệ làm lại; chênh lệch được phát hiện.',
        'So sánh với cách quản lý bằng Excel trước đây.',
        'Ý kiến của đơn vị sử dụng.'],
      'Bảng 5.9: Số liệu vận hành. Hình 5.5: Dashboard tiến độ dự án.',
      'Minh chứng hệ thống dùng được trong thực tế.'],
  ]],

  ['KẾT LUẬN VÀ HƯỚNG PHÁT TRIỂN',
    'Tổng kết kết quả, nêu hạn chế và hướng phát triển.', [
    ['Kết quả đạt được',
      'Đối chiếu kết quả với mục tiêu đặt ra ở phần Mở đầu.',
      ['Hệ thống quản lý khép kín 7 công đoạn đã triển khai.',
        'Module OCR trích xuất 5 trường với độ chính xác đo được.',
        'Hiệu quả tiết kiệm thời gian nhập liệu.', 'Các đóng góp chính của đề tài.'],
      'Bảng: Đối chiếu mục tiêu và kết quả.', 'Khẳng định mức độ hoàn thành.'],
    ['Hạn chế',
      'Nêu trung thực những điểm chưa làm được.',
      ['Chưa xử lý chữ viết tay, bảng biểu phức tạp.', 'Bộ dữ liệu đánh giá còn giới hạn ở một dự án.',
        'Ký số chưa tích hợp trực tiếp.'],
      'Không có', 'Nhận diện giới hạn của đề tài.'],
    ['Hướng phát triển',
      'Đề xuất bước tiếp theo.',
      ['Mở rộng trích xuất sang toàn bộ metadata hồ sơ và văn bản.', 'Tinh chỉnh mô hình trên dữ liệu tích lũy từ kiểm tra của con người.',
        'Tích hợp ký số, đóng gói SIP theo chuẩn của cơ quan lưu trữ.', 'Chuyển giao diện sang framework hiện đại, triển khai bằng container.'],
      'Không có', 'Lộ trình phát triển tiếp theo.'],
  ]],

  ['PHỤ LỤC', 'Các tài liệu bổ sung.', [
    ['Phụ lục A. Đặc tả yêu cầu nghiệp vụ',
      'Đưa toàn bộ tài liệu BA vào báo cáo.',
      ['Yêu cầu chức năng, user story, tiêu chí chấp nhận, quy tắc nghiệp vụ, ma trận truy vết.'],
      'Không có', 'Tài liệu tham chiếu đầy đủ.'],
    ['Phụ lục B. Hướng dẫn cài đặt và sử dụng',
      'Giúp người khác cài đặt và dùng hệ thống.',
      ['Yêu cầu phần cứng, phần mềm; các bước cài đặt; hướng dẫn theo từng vai trò.'],
      'Không có', 'Hệ thống có thể chuyển giao.'],
  ]],
];

module.exports.plan = [
  ['Tuần 1', 'Khảo sát đơn vị, phân tích nghiệp vụ, lập tài liệu BA, chốt đề cương', 'Tài liệu BA, đề cương chi tiết'],
  ['Tuần 2', 'Nền tảng quy trình, tài khoản cộng tác viên, cấu hình dự án, import mục lục', 'Module cấu hình và chỉnh lý'],
  ['Tuần 3', 'Giao việc, nộp gói scan, so khớp đường dẫn, kiểm tra scan, kiểm tra nhập liệu hai vòng', 'Module scan và kiểm tra'],
  ['Tuần 4', 'Chuẩn hóa, bàn giao, sản lượng, KPI; chạy thử và chạy thật tại đơn vị', 'Bản hệ thống vận hành thật'],
  ['Tuần 5', 'Nghiên cứu tiền xử lý ảnh và OCR tiếng Việt; dựng thí nghiệm so sánh engine', 'Kết quả so sánh OCR'],
  ['Tuần 6', 'Xây dựng bộ dữ liệu đánh giá từ kết quả kiểm tra', 'Bộ dữ liệu có nhãn'],
  ['Tuần 7–8', 'Xây dựng module trích xuất 5 trường, kiểm tra chất lượng ảnh', 'Module OCR hoàn chỉnh'],
  ['Tuần 9', 'Tích hợp gợi ý vào màn hình nhập liệu; thí nghiệm đối chứng', 'Số liệu hiệu quả nhập liệu'],
  ['Tuần 10', 'Kiểm thử chức năng, hiệu năng, bảo mật; hoàn thiện', 'Báo cáo kiểm thử'],
  ['Tuần 11', 'Viết báo cáo Chương 1–3', 'Bản thảo nửa đầu'],
  ['Tuần 12', 'Viết báo cáo Chương 4–5, kết luận; làm slide', 'Báo cáo hoàn chỉnh, slide bảo vệ'],
];

module.exports.abbreviations = [
  ['AI', 'Trí tuệ nhân tạo (Artificial Intelligence)'],
  ['API', 'Giao diện lập trình ứng dụng'],
  ['BA', 'Phân tích nghiệp vụ (Business Analysis)'],
  ['CER / WER', 'Tỉ lệ lỗi ký tự / tỉ lệ lỗi từ'],
  ['CS', 'Gói scan đã qua kiểm tra (Checked Scan)'],
  ['CTV', 'Cộng tác viên'],
  ['KPI', 'Chỉ số đo lường hiệu suất'],
  ['OAIS', 'Mô hình hệ thống thông tin lưu trữ mở (ISO 14721)'],
  ['OCR', 'Nhận dạng ký tự quang học'],
  ['PDF/A', 'Định dạng PDF dùng cho lưu trữ lâu dài (ISO 19005)'],
  ['S', 'Gói scan do người scan nộp'],
  ['SIP', 'Gói thông tin nộp lưu (Submission Information Package)'],
  ['UAT', 'Kiểm thử chấp nhận của người dùng'],
];

module.exports.references = [
  'Quốc hội (2024), Luật Lưu trữ số 33/2024/QH15.',
  'Chính phủ (2023), Nghị định 13/2023/NĐ-CP về bảo vệ dữ liệu cá nhân.',
  'Bộ Nội vụ (2019), Thông tư 02/2019/TT-BNV quy định tiêu chuẩn dữ liệu thông tin đầu vào và yêu cầu bảo quản tài liệu lưu trữ điện tử.',
  'ISO 19005 – Document management: Electronic document file format for long-term preservation (PDF/A).',
  'ISO 14721 – Space data and information transfer systems: Open Archival Information System (OAIS) Reference Model.',
  'R. Smith (2007), An Overview of the Tesseract OCR Engine, Proc. ICDAR 2007.',
  'Y. Du et al. (2020), PP-OCR: A Practical Ultra Lightweight OCR System, arXiv:2009.09941.',
  'VietOCR – Vietnamese OCR toolkit, https://github.com/pbcquoc/vietocr.',
  'PaddleOCR, https://github.com/PaddlePaddle/PaddleOCR.',
  'Y. Xu et al. (2020), LayoutLM: Pre-training of Text and Layout for Document Image Understanding, KDD 2020.',
  'N. Otsu (1979), A Threshold Selection Method from Gray-Level Histograms, IEEE Trans. SMC.',
  'OpenCV documentation, https://docs.opencv.org.',
  'OCRmyPDF, https://github.com/ocrmypdf/OCRmyPDF; veraPDF, https://verapdf.org.',
  'Archivematica, https://github.com/artefactual/archivematica.',
  'Paperless-ngx, https://github.com/paperless-ngx/paperless-ngx.',
  'FastAPI documentation, https://fastapi.tiangolo.com.',
  'SQLAlchemy và Alembic documentation, https://www.sqlalchemy.org.',
  'PostgreSQL documentation, https://www.postgresql.org/docs/.',
  'Locust – load testing, https://locust.io.',
  'M. Fowler (2002), Patterns of Enterprise Application Architecture, Addison-Wesley (mẫu Repository).',
];
