// Chương 3, Chương 4.
module.exports.chapters = [
  ['CHƯƠNG 3. PHÂN TÍCH VÀ THIẾT KẾ HỆ THỐNG',
    'Chương này phân tích yêu cầu và trình bày thiết kế hệ thống: tác nhân, quy trình nghiệp vụ, use case, máy trạng thái, cơ sở dữ liệu, kiến trúc, module OCR và giao diện.', [
    ['3.1. Xác định tác nhân và yêu cầu hệ thống',
      'Xác định ai dùng hệ thống và hệ thống phải làm gì.',
      ['Tác nhân và vai trò:',
        ['Quản trị (Admin/PM): cấu hình dự án, quản lý tài khoản, giao việc, chuẩn hóa, bàn giao, duyệt chi trả.',
          'Nhân sự hành chính: chỉnh lý, scan, kiểm tra scan, nhập liệu, kiểm tra nhập liệu.',
          'Cộng tác viên: chỉ nhập liệu việc được giao, không tải PDF, tài khoản có thời hạn.'],
        'Yêu cầu chức năng nhóm theo module (khoảng 46 yêu cầu, có mã FR để truy vết).',
        'Yêu cầu phi chức năng: hiệu năng (100 người dùng đồng thời), khả dụng 24/7, bảo mật, sao lưu, tương thích.',
        'Quy tắc nghiệp vụ chính: không tự kiểm tra việc của mình, chặn duyệt khi còn chênh lệch, tính tiền khi đã kiểm tra đạt.',
        'Ma trận phân quyền theo vai trò.'],
      'Bảng 3.1: Tác nhân và mô tả. Bảng 3.2: Danh sách yêu cầu chức năng. Bảng 3.3: Yêu cầu phi chức năng. Bảng 3.4: Ma trận phân quyền.',
      'Bộ yêu cầu đầy đủ, truy vết được tới thiết kế và kiểm thử.'],
    ['3.2. Mô hình hóa quy trình nghiệp vụ hiện tại và đề xuất',
      'So sánh cách làm hiện tại với cách làm trên hệ thống mới.',
      ['Quy trình hiện tại (as-is): các bước làm thủ công, điểm nghẽn, nơi phát sinh sai lệch.',
        'Quy trình đề xuất (to-be): các bước trên hệ thống, điểm kiểm soát chất lượng, vị trí AI hỗ trợ.',
        'Các điểm cải tiến: so khớp đường dẫn bắt buộc, kiểm tra hai vòng, gợi ý metadata, đối soát tự động.'],
      'Hình 3.1: Biểu đồ hoạt động quy trình hiện tại. Hình 3.2: Biểu đồ hoạt động quy trình đề xuất.',
      'Thể hiện rõ giá trị của hệ thống so với cách làm cũ.'],
    ['3.3. Biểu đồ use case và đặc tả use case chính',
      'Mô tả tương tác giữa người dùng và hệ thống.',
      ['Biểu đồ use case tổng quát và phân rã theo từng nhóm chức năng.',
        'Đặc tả chi tiết các use case chính (tác nhân, tiền điều kiện, luồng chính, luồng thay thế, hậu điều kiện):',
        ['Import mục lục chỉnh lý.', 'Nộp gói scan và so khớp đường dẫn.', 'Kiểm tra scan.',
          'Nhập liệu có gợi ý OCR.', 'Kiểm tra nhập liệu vòng 2 (lấy mẫu).', 'Thu hồi và phân lại việc của cộng tác viên.',
          'Đóng gói bàn giao.'],
        'Biểu đồ tuần tự cho use case nhập liệu có gợi ý OCR.'],
      'Hình 3.3: Use case tổng quát. Hình 3.4–3.8: Use case phân rã. Hình 3.9: Biểu đồ tuần tự nhập liệu có gợi ý OCR. Bảng 3.5–3.11: Đặc tả use case.',
      'Đặc tả đủ để cài đặt và viết kịch bản kiểm thử.'],
    ['3.4. Thiết kế máy trạng thái cho quy trình 7 công đoạn',
      'Thiết kế cơ chế điều khiển trạng thái của từng hộp hồ sơ qua các công đoạn.',
      ['Danh mục công đoạn, loại công đoạn (thực hiện, kiểm tra, bàn giao), vai trò được phép.',
        'Bốn trạng thái: chờ, đang làm, hoàn tất, bị trả lại; điều kiện bắt đầu và hoàn tất.',
        'Quy tắc trả lại của công đoạn kiểm tra và quy tắc chặn khi công đoạn sau đã bắt đầu.',
        'Công đoạn nhập liệu và kiểm tra nhập liệu được suy ra từ dữ liệu nhập.',
        'Vòng đời gói scan: đã giao, đang scan, đã nộp, lệch đường dẫn, đang kiểm tra, cần làm lại, đã duyệt, đã đóng.'],
      'Hình 3.10: Biểu đồ trạng thái công đoạn. Hình 3.11: Biểu đồ trạng thái gói scan. Bảng 3.12: Bảng chuyển trạng thái.',
      'Thiết kế máy trạng thái có thể cài đặt và kiểm thử độc lập.'],
    ['3.5. Thiết kế cơ sở dữ liệu',
      'Thiết kế lưu trữ dữ liệu cho toàn bộ hệ thống.',
      ['Mô hình thực thể liên kết: dự án, phông, hộp, hồ sơ, file, gói scan, chênh lệch, kiểm tra, lỗi, bản ghi metadata, giờ công, sản lượng, gói bàn giao, nhật ký.',
        'Thiết kế bảng cho module quy trình: trạng thái công đoạn, sự kiện, thành viên theo công đoạn.',
        'Thiết kế bảng cho module OCR: kết quả OCR theo trang, gợi ý trích xuất, độ tin cậy, phiên bản engine.',
        'Ràng buộc toàn vẹn, chỉ mục, khóa ngoại; nguyên tắc chỉ thêm bảng mới, không sửa bảng cũ.',
        'Chiến lược migration và tương thích dữ liệu đang chạy.'],
      'Hình 3.12: Sơ đồ thực thể liên kết. Bảng 3.13–3.20: Mô tả các bảng chính.',
      'Lược đồ cơ sở dữ liệu hoàn chỉnh.'],
    ['3.6. Thiết kế kiến trúc và giao diện lập trình (API)',
      'Thiết kế cấu trúc phần mềm và các API.',
      ['Kiến trúc tổng thể: trình duyệt, máy chủ web, cơ sở dữ liệu, kho file, tiến trình OCR chạy nền.',
        'Phân lớp router, service, repository; vị trí của máy trạng thái và module OCR.',
        'Danh sách API theo nhóm: cấu hình dự án, quy trình, scan, nhập liệu, OCR, bàn giao.',
        'Xử lý tác vụ nặng (quét thư mục, OCR, chuyển PDF/A) bằng tác vụ nền có theo dõi tiến độ.',
        'Thiết kế bảo mật: xác thực, phân quyền theo dự án và công đoạn, ghi nhật ký.'],
      'Hình 3.13: Kiến trúc triển khai. Hình 3.14: Sơ đồ thành phần. Bảng 3.21: Danh sách API.',
      'Kiến trúc đáp ứng yêu cầu chức năng và phi chức năng.'],
    ['3.7. Thiết kế module OCR trích xuất thông tin văn bản hành chính',
      'Thiết kế chi tiết phần AI, trọng tâm của đề tài.',
      ['Luồng xử lý:',
        ['Lấy trang đầu của file PDF, chuyển sang ảnh.',
          'Kiểm tra chất lượng ảnh; cảnh báo nếu mờ, nghiêng, độ phân giải thấp.',
          'Tiền xử lý: chỉnh nghiêng, khử nhiễu, nhị phân hóa.',
          'Chia vùng theo thể thức văn bản: vùng trên trái, trên phải, giữa trang.',
          'Chạy OCR trên từng vùng.',
          'Trích xuất 5 trường bằng luật và mô hình; chuẩn hóa giá trị.',
          'Tính độ tin cậy, lưu kết quả, gợi ý vào màn hình nhập liệu.'],
        'Thiết kế giao diện giữa module OCR và hệ thống (hàng đợi xử lý, kết quả, phiên bản engine).',
        'Thiết kế để thay engine OCR dễ dàng (phục vụ so sánh).',
        'Cách thu thập phản hồi: giá trị cuối cùng sau kiểm tra được dùng để đo độ chính xác.'],
      'Hình 3.15: Pipeline xử lý OCR. Hình 3.16: Các vùng trích xuất trên văn bản mẫu. Bảng 3.22: Quy tắc trích xuất cho từng trường.',
      'Thiết kế module OCR có thể cài đặt và đánh giá.'],
    ['3.8. Thiết kế giao diện người dùng',
      'Thiết kế các màn hình chính.',
      ['Màn hình quản trị dự án và cấu hình quy trình.',
        'Màn hình nộp gói scan, danh sách chênh lệch, kiểm tra scan từng file.',
        'Màn hình nhập liệu: xem PDF song song biểu mẫu, ô gợi ý có tô màu theo độ tin cậy.',
        'Màn hình kiểm tra nhập liệu vòng 1 và vòng 2.',
        'Màn hình đóng gói bàn giao, dashboard tiến độ.'],
      'Hình 3.17–3.22: Bản phác thảo các màn hình chính.',
      'Giao diện thống nhất, phù hợp với từng vai trò.'],
  ]],

  ['CHƯƠNG 4. XÂY DỰNG VÀ TRIỂN KHAI HỆ THỐNG',
    'Chương này trình bày quá trình cài đặt các module theo thiết kế, tích hợp OCR vào hệ thống và triển khai trên máy chủ thực tế.', [
    ['4.1. Môi trường và công cụ phát triển',
      'Liệt kê môi trường làm việc và công cụ.',
      ['Ngôn ngữ, framework, hệ quản trị cơ sở dữ liệu và phiên bản.',
        'Công cụ: Visual Studio Code, Git/GitHub, Postman, trình duyệt Chrome.',
        'Thư viện OCR và xử lý ảnh: Tesseract, VietOCR, PaddleOCR, OpenCV.',
        'Quy trình làm việc: nhánh Git, mỗi nhiệm vụ một commit, chạy kiểm thử trước khi đẩy mã.'],
      'Bảng 4.1: Môi trường và công cụ.',
      'Người đọc có thể dựng lại môi trường.'],
    ['4.2. Xây dựng các module quản lý quy trình số hóa',
      'Trình bày cài đặt các chức năng nghiệp vụ.',
      ['Module cấu hình dự án, tài khoản và phân quyền theo vai trò.',
        'Module chỉnh lý: import Excel mục lục, theo dõi giao nhận hồ sơ giấy.',
        'Module giao việc theo hộp, thu hồi và phân lại.',
        'Module scan: nộp gói, quét thư mục, lập manifest, so khớp đường dẫn.',
        'Module kiểm tra scan, kiểm tra nhập liệu hai vòng.',
        'Module chuẩn hóa, bàn giao, sản lượng, KPI, đối soát.',
        'Các đoạn mã tiêu biểu: máy trạng thái, kiểm tra quyền, chọn mẫu ngẫu nhiên.'],
      'Hình 4.1–4.6: Ảnh chụp màn hình các module. Đoạn mã 4.1–4.3.',
      'Các module chạy được, đúng thiết kế.'],
    ['4.3. Xây dựng module OCR và trích xuất thông tin',
      'Trình bày cài đặt phần AI.',
      ['Cài đặt bước kiểm tra chất lượng ảnh và tiền xử lý bằng OpenCV.',
        'Tích hợp ba engine OCR qua một giao diện chung.',
        'Cài đặt bộ trích xuất 5 trường: luật, chia vùng, chuẩn hóa giá trị, tính độ tin cậy.',
        'Chạy OCR dạng tác vụ nền, lưu kết quả theo phiên bản.',
        'Xử lý các trường hợp khó: con dấu đè chữ, văn bản nhiều trang, trang đầu không chứa đủ thông tin.'],
      'Hình 4.7: Ảnh trước/sau tiền xử lý. Hình 4.8: Kết quả trích xuất trên văn bản mẫu. Đoạn mã 4.4–4.6.',
      'Module OCR hoạt động trên dữ liệu thật.'],
    ['4.4. Tích hợp gợi ý trích xuất vào màn hình nhập liệu',
      'Đưa kết quả OCR tới người dùng.',
      ['Tự điền 5 trường khi mở văn bản; hiển thị độ tin cậy bằng màu sắc.',
        'Người nhập xác nhận hoặc sửa; hệ thống ghi lại giá trị gợi ý và giá trị cuối cùng.',
        'Đo thời gian nhập liệu trên từng văn bản.',
        'Cho phép bật/tắt gợi ý theo dự án để làm thí nghiệm đối chứng.'],
      'Hình 4.9: Màn hình nhập liệu có gợi ý OCR.',
      'Gợi ý OCR được dùng thật trong quá trình nhập liệu.'],
    ['4.5. Triển khai hệ thống trên máy chủ nội bộ',
      'Trình bày cách đưa hệ thống vào vận hành.',
      ['Cấu hình máy chủ Windows, PostgreSQL, Caddy (HTTPS), dịch vụ chạy nền.',
        'Đồng bộ file scan từ máy trạm qua mạng nội bộ.',
        'Cho cộng tác viên truy cập qua Internet; các biện pháp bảo mật tối thiểu.',
        'Sao lưu hằng ngày và thử khôi phục.',
        'Quy trình cập nhật phiên bản và chạy migration.'],
      'Hình 4.10: Sơ đồ triển khai thực tế.',
      'Hệ thống chạy ổn định tại đơn vị.'],
    ['4.6. Kết quả giao diện chương trình',
      'Trình bày các màn hình hoàn chỉnh.',
      ['Đăng nhập, quản trị, cấu hình dự án.',
        'Quy trình số hóa, danh sách hộp theo công đoạn.',
        'Kiểm tra scan, nhập liệu có gợi ý OCR, kiểm tra nhập liệu.',
        'Đóng gói bàn giao, dashboard, thông báo.'],
      'Hình 4.11–4.20: Ảnh chụp màn hình.',
      'Minh chứng sản phẩm hoàn chỉnh.'],
  ]],
];
